services:
  citas_evaluaciones_postgres:
    image: postgres:17.7
    container_name: grupo3-citas-evaluaciones-postgres
    environment:
      POSTGRES_DB: nurtricenter_db
      POSTGRES_USER: citas_evaluaciones_user
      POSTGRES_PASSWORD: SuperUsuar10
    ports:
      - "5434:5432"
    volumes:
      - citas_evaluaciones_postgres_data:/var/lib/postgresql/data

  citas_evaluaciones:
    build: .
    container_name: citas_evaluaciones
    hostname: citas-evaluaciones
    depends_on:
      - citas_evaluaciones_postgres
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://citas_evaluaciones_postgres:5432/nurtricenter_db
      DB_USER: citas_evaluaciones_user
      DB_PASSWORD: SuperUsuar10
      LOKI_URL: ${LOKI_URL:-http://154.38.180.80:3100}
      CONSUL_ENABLED: ${CONSUL_ENABLED:-true}
      CONSUL_HOST: ${CONSUL_HOST:-154.38.180.80}
      CONSUL_PORT: ${CONSUL_PORT:-8500}
      SERVICE_ID: ${SERVICE_ID:-nur-tricenter-appointments}
      SERVICE_NAME: ${SERVICE_NAME:-nur-tricenter-appointments}
      SERVICE_ADDRESS: ${SERVICE_ADDRESS:-146.190.116.159}
      SERVICE_PORT: ${SERVICE_PORT:-9004}
      HEALTH_CHECK_PATH: ${HEALTH_CHECK_PATH:-/actuator/health}
      HEALTH_CHECK_INTERVAL: ${HEALTH_CHECK_INTERVAL:-15s}
      HEALTH_CHECK_TIMEOUT: ${HEALTH_CHECK_TIMEOUT:-5s}
      CONSUL_DEREGISTER_AFTER: ${CONSUL_DEREGISTER_AFTER:-1m}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9004:8080"
    restart: unless-stopped

volumes:
  citas_evaluaciones_postgres_data:
