services:
  citas_evaluaciones_postgres:
    image: postgres:17.7
    container_name: grupo3-citas-evaluaciones-postgres
    environment:
      POSTGRES_DB: nurtricenter_db
      POSTGRES_USER: citas_evaluaciones_user
      POSTGRES_PASSWORD: SuperUsuar10
    ports:
      - "5434:5432"
    volumes:
      - citas_evaluaciones_postgres_data:/var/lib/postgresql/data

  citas_evaluaciones:
    build: .
    container_name: citas_evaluaciones
    depends_on:
      - citas_evaluaciones_postgres
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://citas_evaluaciones_postgres:5432/nurtricenter_db
      DB_USER: citas_evaluaciones_user
      DB_PASSWORD: SuperUsuar10
    ports:
      - "9004:8080"

volumes:
  citas_evaluaciones_postgres_data: