#!/bin/sh

echo "Checking formatting..."

./mvnw spotless:check

if [ $? -ne 0 ]; then
	echo "Formatting errors detected"
	echo "Running: mvn spotless:apply"
	./mvnw spotless:apply
	exit 0
fi

echo "Running unit tests..."

./mvnw test

if [ $? -ne 0 ]; then
	echo "Unit tests failed. Commit aborted."
	exit 1
fi
